# Generated by Django 4.2.3 on 2023-07-27 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_profile_remove_user_check_birth_date_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="check_birth_date",
        ),
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "birth_date__lte",
                        datetime.datetime(2008, 7, 30, 10, 40, 23, 470719),
                    )
                ),
                name="check_birth_date",
            ),
        ),
    ]
